### PR TITLE
Add "Negotiated Terms"

### PR DESCRIPTION
**Pull request by kemitchell**
@anseljh: I'd be particularly grateful for your quick read of this addition.

The comments to the new section give some idea why I think terms like this might actually work.  That being said, I couldn't find a single California case law example in practice.

### CODE REVIEW

**Comment by anseljh** [comment]
Interesting. Looks good at first glance. I will take a closer look.

**Comment by kemitchell** [comment]
@anseljh Thanks again for any input you might have time to provide!

**Comment by anseljh** [comment]
This looks good to me, but it'd be great to check the Restatement (Second) of Contracts next time one of us is at a law library.

**Comment by kemitchell** [comment]
I'm going to go ahead and merge.  Not to dismiss the Restatement, but the scope here is California-only, where the principle resides in code.  There's wiggle room under the cases, and courts cite restatements as secondary almost by reflex, but I think I've seen the authority that matters.

**Pull request merged**
